included:
  - AllisonsCatPalaceTDD
  - AllisonsCatPalaceTDDTests
excluded:
  - Pods
  - Tests/SwiftLintFrameworkTests/Resources
opt_in_rules:
  - attributes
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - file_header
  - file_length
  - first_where
  - implicit_return
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - statement_position

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  SwiftLint
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} .*?\. All rights reserved\.
                    \/\/
line_length: 120
number_separator:
  minimum_length: 5
