included:
  - AllisonsCatPalaceTDD
  - AllisonsCatPalaceTDDTests
excluded:
  - Pods
  - Tests/SwiftLintFrameworkTests/Resources
opt_in_rules:
  - attributes
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - file_length
  - first_where
  - implicit_return
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - closure_parameter_position
  - statement_position
  - todo

line_length: 120
number_separator:
  minimum_length: 5
