//
//  AnimalBreed.swift
//  AllisonsCatPalaceTDD
//
//  Created by Joe Susnick on 9/23/17.
//  Copyright © 2017 Joesus. All rights reserved.
//

import Foundation
import RealmSwift

class AnimalBreedObject: Object {
    dynamic var value: String? = nil
}

enum AnimalBreed: String, Equatable {

    case abyssinian, affenpinscher, afghanHound, africanGrey, airedaleTerrier, akbash, akita, alaskanMalamute, alpaca, amazon, american, americanBulldog, americanCurl, americanEskimoDog, americanFuzzyLop, americanHairlessTerrier, americanSable, americanShorthair, americanStaffordshireTerrier, americanWaterSpaniel, americanWirehair, anatolianShepherd, angoraRabbit, appaloosa, appenzellMountainDog, appleheadSiamese, arabian, australianCattleDogBlueHeeler, australianKelpie, australianShepherd, australianTerrier, balinese, basenji, bassetHound, beagle, beardedCollie, beauceron, bedlingtonTerrier, belgian, belgianHare, belgianShepherdDogSheepdog, belgianShepherdLaekenois, belgianShepherdMalinois, belgianShepherdTervuren, bengal, berneseMountainDog, beveren, bichonFrise, birman, blackAndTanCoonhound, blackLabradorRetriever, blackMouthCur, blackRussianTerrier, bloodhound, blueLacy, bluetickCoonhound, bobtail, boerboel, bolognese, bombay, borderCollie, borderTerrier, borzoi, bostonTerrier, bouvierDesFlanders, boxer, boykinSpaniel, briard, britanniaPetite, britishShorthair, brittanySpaniel, brotogeris, brusselsGriffon, budgieBudgerigar, bullTerrier, bullmastiff, bunnyRabbit, burmese, burmilla, buttonQuail, caique, cairnTerrier, calico, californian, canaanDog, canadianHairless, canary, caneCorsoMastiff, carolinaDog, catahoulaLeopardDog, cattleDog, caucasianSheepdogCaucasianOvtcharka, cavalierKingCharlesSpaniel, champagneDArgent, chartreux, chausie, checkeredGiant, chesapeakeBayRetriever, chicken, chihuahua, chinchilla, chineseCrestedDog, chineseFooDog, chinook, chocolateLabradorRetriever, chowChow, cinnamon, cirnecoDellEtna, clumberSpaniel, clydesdale, cockapoo, cockatiel, cockatoo, cockerSpaniel, collie, conure, coonhound, corgi, cornishRex, cotonDeTulear, cow, cremeDArgent, curlyCoatedRetriever, curlyHorse, cymric, dachshund, dalmatian, dandiDinmontTerrier, degu, devonRex, diluteCalico, diluteTortoiseshell, dobermanPinscher, dogoArgentino, dogueDeBordeaux, domesticLongHair, domesticLongHairBlack, domesticLongHairBlackAndWhite, domesticLongHairBrown, domesticLongHairBuff, domesticLongHairBuffAndWhite, domesticLongHairGray, domesticLongHairGrayAndWhite, domesticLongHairOrange, domesticLongHairOrangeAndWhite, domesticLongHairWhite, domesticMediumHair, domesticMediumHairBlack, domesticMediumHairBlackAndWhite, domesticMediumHairBrown, domesticMediumHairBuff, domesticMediumHairBuffAndWhite, domesticMediumHairGray, domesticMediumHairGrayAndWhite, domesticMediumHairOrange, domesticMediumHairOrangeAndWhite, domesticMediumHairWhite, domesticShortHair, domesticShortHairBlack, domesticShortHairBlackAndWhite, domesticShortHairBrown, domesticShortHairBuff, domesticShortHairBuffAndWhite, domesticShortHairGray, domesticShortHairGrayAndWhite, domesticShortHairMitted, domesticShortHairOrange, domesticShortHairOrangeAndWhite, domesticShortHairWhite, donkeyMule, dove, draft, duck, dutch, dutchShepherd, dwarf, dwarfEared, eclectus, egyptianMau, emu, englishBulldog, englishCockerSpaniel, englishCoonhound, englishLop, englishPointer, englishSetter, englishShepherd, englishSpot, englishSpringerSpaniel, englishToySpaniel, entlebucher, eskimoDog, exoticShorthair, extraToesCatHemingwayPolydactyl, feist, ferret, fieldSpaniel, filaBrasileiro, finch, finnishLapphund, finnishSpitz, fish, flatCoatedRetriever, flemishGiant, floridaWhite, foxTerrier, foxhound, frenchBulldog, frenchLop, frog, gaited, galgoSpanishGreyhound, gecko, gerbil, germanPinscher, germanShepherdDog, germanShorthairedPointer, germanSpitz, germanWirehairedPointer, giantSchnauzer, glenOfImaalTerrier, goat, goldenRetriever, goose, gordonSetter, grade, greatDane, greatPyrenees, greaterSwissMountainDog, greyhound, guineaFowl, guineaPig, hamster, harlequin, harrier, havana, havanese, hedgehog, hermitCrab, himalayan, hollandLop, hotot, hound, hovawart, husky, ibizanHound, iguana, illyrianSheepdog, irishSetter, irishTerrier, irishWaterSpaniel, irishWolfhound, italianGreyhound, italianSpinone, jackRussellTerrier, jackRussellTerrierParsonRussellTerrier, japaneseBobtail, japaneseChin, javanese, jerseyWooly, jindo, kaiDog, kakariki, karelianBearDog, keeshond, kerryBlueTerrier, kishu, kleeKai, komondor, korat, kuvasz, kyiLeo, labradorRetriever, lakelandTerrier, lancashireHeeler, laperm, leonberger, lhasaApso, lilac, lionhead, lipizzan, lizard, llama, lopEared, loryLorikeet, lovebird, lowchen, macaw, maineCoon, maltese, manchesterTerrier, manx, maremmaSheepdog, mastiff, mcnab, miniLop, miniRex, miniatureHorse, miniaturePinscher, missouriFoxtrotter, morgan, mountainCur, mountainDog, mouse, munchkin, munsterlander, mustang, mynah, neapolitanMastiff, nebelung, netherlandDwarf, newGuineaSingingDog, newZealand, newfoundlandDog, norfolkTerrier, norwegianBuhund, norwegianElkhound, norwegianForestCat, norwegianLundehund, norwichTerrier, novaScotiaDuckTollingRetriever, ocicat, oldEnglishSheepdog, orientalLongHair, orientalShortHair, orientalTabby, ostrich, otterhound, paintPinto, palomino, papillon, parakeetOther, parrotOther, parrotlet, pasoFino, patterdaleTerrierFellTerrier, peacockPeaFowl, pekingese, percheron, persian, peruvianIncaOrchid, peruvianPaso, petitBassetGriffonVendeen, pharaohHound, pheasant, pig, pigeon, pionus, pitBullTerrier, pixieBob, plottHound, podengoPortugueso, poicephalusSenegal, pointer, polish, polishLowlandSheepdog, pomeranian, pony, poodle, portugueseWaterDog, potBellied, prairieDog, presaCanario, pug, puli, pumi, quail, quakerParakeet, quarterhorse, ragamuffin, ragdoll, rat, ratTerrier, redboneCoonhound, retriever, rex, rhea, rhinelander, rhodesianRidgeback, ringneckPsittacula, rosella, rottweiler, russianBlue, saddlebred, saintBernardStBernard, saluki, samoyed, sarplaninac, satin, schipperke, schnauzer, scottishDeerhound, scottishFold, scottishTerrierScottie, sealyhamTerrier, selkirkRex, setter, sharPei, sheep, sheepDog, shepherd, shetlandPony, shetlandSheepdogSheltie, shibaInu, shihTzu, siamese, siberian, siberianHusky, silkyTerrier, silver, silverFox, silverMarten, singapura, skunk, skyeTerrier, sloughi, smoothFoxTerrier, snake, snowshoe, softbillOther, somali, southRussianOvtcharka, spaniel, sphynxHairlessCat, spitz, staffordshireBullTerrier, standardPoodle, standardbred, sugarGlider, sussexSpaniel, swedishVallhund, tabby, tabbyBlack, tabbyBrown, tabbyBuff, tabbyGrey, tabbyOrange, tabbyWhite, tan, tarantula, tennesseeWalker, terrier, thaiRidgeback, thoroughbred, tibetanMastiff, tibetanSpaniel, tibetanTerrier, tiger, tonkinese, torbie, tortoiseshell, tosaInu, toyFoxTerrier, treeingWalkerCoonhound, turkishAngora, turkishVan, turtle, tuxedo, unknown, vietnamesePotBellied, vizsla, warmblood, weimaraner, welshCorgi, welshSpringerSpaniel, welshTerrier, westHighlandWhiteTerrierWestie, wheatenTerrier, whippet, whiteGermanShepherd, wireFoxTerrier, wireHairedPointingGriffon, wirehairedTerrier, xoloitzcuintleMexicanHairless, yellowLabradorRetriever, yorkshireTerrierYorkie


    init?(petFinderRawValue: String) {
        print(AnimalBreed.petFinderRawValueMapping.keys)
        guard let breed = AnimalBreed.petFinderRawValueMapping[petFinderRawValue] else {
            return nil
        }
        self = breed
    }
}

extension AnimalBreed: Persistable {
    typealias ManagedObject = AnimalBreedObject

    var managedObject: ManagedObject {
        let object = AnimalBreedObject()

        object.value = self.rawValue

        return object
    }

    init?(managedObject: ManagedObject) {
        guard let value = managedObject.value else {
            return nil
        }
        self.init(rawValue: value)
    }
}

extension AnimalBreed {
    static let petFinderRawValueMapping: [String: AnimalBreed] =
        ["Abyssinian": .abyssinian,
         "Affenpinscher": .affenpinscher,
         "Afghan Hound": .afghanHound,
         "African Grey": .africanGrey,
         "Airedale Terrier": .airedaleTerrier,
         "Akbash": .akbash,
         "Akita": .akita,
         "Alaskan Malamute": .alaskanMalamute,
         "Alpaca": .alpaca,
         "Amazon": .amazon,
         "American": .american,
         "American Bulldog": .americanBulldog,
         "American Curl": .americanCurl,
         "American Eskimo Dog": .americanEskimoDog,
         "American Fuzzy Lop": .americanFuzzyLop,
         "American Hairless Terrier": .americanHairlessTerrier,
         "American Sable": .americanSable,
         "American Shorthair": .americanShorthair,
         "American Staffordshire Terrier": .americanStaffordshireTerrier,
         "American Water Spaniel": .americanWaterSpaniel,
         "American Wirehair": .americanWirehair,
         "Anatolian Shepherd": .anatolianShepherd,
         "Angora Rabbit": .angoraRabbit,
         "Appaloosa": .appaloosa,
         "Appenzell Mountain Dog": .appenzellMountainDog,
         "Applehead Siamese": .appleheadSiamese,
         "Arabian": .arabian,
         "Australian Cattle Dog/Blue Heeler": .australianCattleDogBlueHeeler,
         "Australian Kelpie": .australianKelpie,
         "Australian Shepherd": .australianShepherd,
         "Australian Terrier": .australianTerrier,
         "Balinese": .balinese,
         "Basenji": .basenji,
         "Basset Hound": .bassetHound,
         "Beagle": .beagle,
         "Bearded Collie": .beardedCollie,
         "Beauceron": .beauceron,
         "Bedlington Terrier": .bedlingtonTerrier,
         "Belgian": .belgian,
         "Belgian Hare": .belgianHare,
         "Belgian Shepherd Dog Sheepdog": .belgianShepherdDogSheepdog,
         "Belgian Shepherd Laekenois": .belgianShepherdLaekenois,
         "Belgian Shepherd Malinois": .belgianShepherdMalinois,
         "Belgian Shepherd Tervuren": .belgianShepherdTervuren,
         "Bengal": .bengal,
         "Bernese Mountain Dog": .berneseMountainDog,
         "Beveren": .beveren,
         "Bichon Frise": .bichonFrise,
         "Birman": .birman,
         "Black Labrador Retriever": .blackLabradorRetriever,
         "Black Mouth Cur": .blackMouthCur,
         "Black Russian Terrier": .blackRussianTerrier,
         "Black and Tan Coonhound": .blackAndTanCoonhound,
         "Bloodhound": .bloodhound,
         "Blue Lacy": .blueLacy,
         "Bluetick Coonhound": .bluetickCoonhound,
         "Bobtail": .bobtail,
         "Boerboel": .boerboel,
         "Bolognese": .bolognese,
         "Bombay": .bombay,
         "Border Collie": .borderCollie,
         "Border Terrier": .borderTerrier,
         "Borzoi": .borzoi,
         "Boston Terrier": .bostonTerrier,
         "Bouvier des Flanders": .bouvierDesFlanders,
         "Boxer": .boxer,
         "Boykin Spaniel": .boykinSpaniel,
         "Briard": .briard,
         "Britannia Petite": .britanniaPetite,
         "British Shorthair": .britishShorthair,
         "Brittany Spaniel": .brittanySpaniel,
         "Brotogeris": .brotogeris,
         "Brussels Griffon": .brusselsGriffon,
         "Budgie/Budgerigar": .budgieBudgerigar,
         "Bull Terrier": .bullTerrier,
         "Bullmastiff": .bullmastiff,
         "Bunny Rabbit": .bunnyRabbit,
         "Burmese": .burmese,
         "Burmilla": .burmilla,
         "Button Quail": .buttonQuail,
         "Caique": .caique,
         "Cairn Terrier": .cairnTerrier,
         "Calico": .calico,
         "Californian": .californian,
         "Canaan Dog": .canaanDog,
         "Canadian Hairless": .canadianHairless,
         "Canary": .canary,
         "Cane Corso Mastiff": .caneCorsoMastiff,
         "Carolina Dog": .carolinaDog,
         "Catahoula Leopard Dog": .catahoulaLeopardDog,
         "Cattle Dog": .cattleDog,
         "Caucasian Sheepdog (Caucasian Ovtcharka)": .caucasianSheepdogCaucasianOvtcharka,
         "Cavalier King Charles Spaniel": .cavalierKingCharlesSpaniel,
         "Champagne D\'Argent": .champagneDArgent,
         "Chartreux": .chartreux,
         "Chausie": .chausie,
         "Checkered Giant": .checkeredGiant,
         "Chesapeake Bay Retriever": .chesapeakeBayRetriever,
         "Chicken": .chicken,
         "Chihuahua": .chihuahua,
         "Chinchilla": .chinchilla,
         "Chinese Crested Dog": .chineseCrestedDog,
         "Chinese Foo Dog": .chineseFooDog,
         "Chinook": .chinook,
         "Chocolate Labrador Retriever": .chocolateLabradorRetriever,
         "Chow Chow": .chowChow,
         "Cinnamon": .cinnamon,
         "Cirneco dell\'Etna": .cirnecoDellEtna,
         "Clumber Spaniel": .clumberSpaniel,
         "Clydesdale": .clydesdale,
         "Cockapoo": .cockapoo,
         "Cockatiel": .cockatiel,
         "Cockatoo": .cockatoo,
         "Cocker Spaniel": .cockerSpaniel,
         "Collie": .collie,
         "Conure": .conure,
         "Coonhound": .coonhound,
         "Corgi": .corgi,
         "Cornish Rex": .cornishRex,
         "Coton de Tulear": .cotonDeTulear,
         "Cow": .cow,
         "Creme D\'Argent": .cremeDArgent,
         "Curly Horse": .curlyHorse,
         "Curly-Coated Retriever": .curlyCoatedRetriever,
         "Cymric": .cymric,
         "Dachshund": .dachshund,
         "Dalmatian": .dalmatian,
         "Dandi Dinmont Terrier": .dandiDinmontTerrier,
         "Degu": .degu,
         "Devon Rex": .devonRex,
         "Dilute Calico": .diluteCalico,
         "Dilute Tortoiseshell": .diluteTortoiseshell,
         "Doberman Pinscher": .dobermanPinscher,
         "Dogo Argentino": .dogoArgentino,
         "Dogue de Bordeaux": .dogueDeBordeaux,
         "Domestic Long Hair": .domesticLongHair,
         "Domestic Long Hair - brown": .domesticLongHairBrown,
         "Domestic Long Hair - buff": .domesticLongHairBuff,
         "Domestic Long Hair - buff and white": .domesticLongHairBuffAndWhite,
         "Domestic Long Hair - gray and white": .domesticLongHairGrayAndWhite,
         "Domestic Long Hair - orange": .domesticLongHairOrange,
         "Domestic Long Hair - orange and white": .domesticLongHairOrangeAndWhite,
         "Domestic Long Hair-black": .domesticLongHairBlack,
         "Domestic Long Hair-black and white":  .domesticLongHairBlackAndWhite,
         "Domestic Long Hair-gray": .domesticLongHairGray,
         "Domestic Long Hair-white": .domesticLongHairWhite,
         "Domestic Medium Hair": .domesticMediumHair,
         "Domestic Medium Hair - brown": .domesticMediumHairBrown,
         "Domestic Medium Hair - buff": .domesticMediumHairBuff,
         "Domestic Medium Hair - buff and white": .domesticMediumHairBuffAndWhite,
         "Domestic Medium Hair - gray and white": .domesticMediumHairGrayAndWhite,
         "Domestic Medium Hair - orange and white": .domesticMediumHairOrangeAndWhite,
         "Domestic Medium Hair-black": .domesticMediumHairBlack,
         "Domestic Medium Hair-black and white": .domesticMediumHairBlackAndWhite,
         "Domestic Medium Hair-gray": .domesticMediumHairGray,
         "Domestic Medium Hair-orange": .domesticMediumHairOrange,
         "Domestic Medium Hair-white": .domesticMediumHairWhite,
         "Domestic Short Hair": .domesticShortHair,
         "Domestic Short Hair - brown": .domesticShortHairBrown,
         "Domestic Short Hair - buff": .domesticShortHairBuff,
         "Domestic Short Hair - buff and white": .domesticShortHairBuffAndWhite,
         "Domestic Short Hair - gray and white": .domesticShortHairGrayAndWhite,
         "Domestic Short Hair - orange and white": .domesticShortHairOrangeAndWhite,
         "Domestic Short Hair-black": .domesticShortHairBlack,
         "Domestic Short Hair-black and white": .domesticShortHairBlackAndWhite,
         "Domestic Short Hair-gray": .domesticShortHairGray,
         "Domestic Short Hair-mitted": .domesticShortHairMitted,
         "Domestic Short Hair-orange": .domesticShortHairOrange,
         "Domestic Short Hair-white": .domesticShortHairWhite,
         "Donkey/Mule": .donkeyMule,
         "Dove": .dove,
         "Draft": .draft,
         "Duck": .duck,
         "Dutch": .dutch,
         "Dutch Shepherd": .dutchShepherd,
         "Dwarf": .dwarf,
         "Dwarf Eared": .dwarfEared,
         "Eclectus": .eclectus,
         "Egyptian Mau": .egyptianMau,
         "Emu": .emu,
         "English Bulldog": .englishBulldog,
         "English Cocker Spaniel": .englishCockerSpaniel,
         "English Coonhound": .englishCoonhound,
         "English Lop": .englishLop,
         "English Pointer": .englishPointer,
         "English Setter": .englishSetter,
         "English Shepherd": .englishShepherd,
         "English Spot": .englishSpot,
         "English Springer Spaniel": .englishSpringerSpaniel,
         "English Toy Spaniel": .englishToySpaniel,
         "Entlebucher": .entlebucher,
         "Eskimo Dog": .eskimoDog,
         "Exotic Shorthair": .exoticShorthair,
         "Extra-Toes Cat (Hemingway Polydactyl)": .extraToesCatHemingwayPolydactyl,
         "Feist": .feist,
         "Ferret": .ferret,
         "Field Spaniel": .fieldSpaniel,
         "Fila Brasileiro": .filaBrasileiro,
         "Finch": .finch,
         "Finnish Lapphund": .finnishLapphund,
         "Finnish Spitz": .finnishSpitz,
         "Fish": .fish,
         "Flat-coated Retriever": .flatCoatedRetriever,
         "Flemish Giant": .flemishGiant,
         "Florida White": .floridaWhite,
         "Fox Terrier": .foxTerrier,
         "Foxhound": .foxhound,
         "French Bulldog": .frenchBulldog,
         "French-Lop": .frenchLop,
         "Frog": .frog,
         "Gaited": .gaited,
         "Galgo Spanish Greyhound": .galgoSpanishGreyhound,
         "Gecko": .gecko,
         "Gerbil": .gerbil,
         "German Pinscher": .germanPinscher,
         "German Shepherd Dog": .germanShepherdDog,
         "German Shorthaired Pointer": .germanShorthairedPointer,
         "German Spitz": .germanSpitz,
         "German Wirehaired Pointer": .germanWirehairedPointer,
         "Giant Schnauzer": .giantSchnauzer,
         "Glen of Imaal Terrier": .glenOfImaalTerrier,
         "Goat": .goat,
         "Golden Retriever": .goldenRetriever,
         "Goose": .goose,
         "Gordon Setter": .gordonSetter,
         "Grade": .grade,
         "Great Dane": .greatDane,
         "Great Pyrenees": .greatPyrenees,
         "Greater Swiss Mountain Dog": .greaterSwissMountainDog,
         "Greyhound": .greyhound,
         "Guinea Pig": .guineaPig,
         "Guinea fowl": .guineaFowl,
         "Hamster": .hamster,
         "Harlequin": .harlequin,
         "Harrier": .harrier,
         "Havana": .havana,
         "Havanese": .havanese,
         "Hedgehog": .hedgehog,
         "Hermit Crab": .hermitCrab,
         "Himalayan": .himalayan,
         "Holland Lop": .hollandLop,
         "Hotot": .hotot,
         "Hound": .hound,
         "Hovawart": .hovawart,
         "Husky": .husky,
         "Ibizan Hound": .ibizanHound,
         "Iguana": .iguana,
         "Illyrian Sheepdog": .illyrianSheepdog,
         "Irish Setter": .irishSetter,
         "Irish Terrier": .irishTerrier,
         "Irish Water Spaniel": .irishWaterSpaniel,
         "Irish Wolfhound": .irishWolfhound,
         "Italian Greyhound": .italianGreyhound,
         "Italian Spinone": .italianSpinone,
         "Jack Russell Terrier": .jackRussellTerrier,
         "Jack Russell Terrier (Parson Russell Terrier)": .jackRussellTerrierParsonRussellTerrier,
         "Japanese Bobtail": .japaneseBobtail,
         "Japanese Chin": .japaneseChin,
         "Javanese": .javanese,
         "Jersey Wooly": .jerseyWooly,
         "Jindo": .jindo,
         "Kai Dog": .kaiDog,
         "Kakariki": .kakariki,
         "Karelian Bear Dog": .karelianBearDog,
         "Keeshond": .keeshond,
         "Kerry Blue Terrier": .kerryBlueTerrier,
         "Kishu": .kishu,
         "Klee Kai": .kleeKai,
         "Komondor": .komondor,
         "Korat": .korat,
         "Kuvasz": .kuvasz,
         "Kyi Leo": .kyiLeo,
         "LaPerm": .laperm,
         "Labrador Retriever": .labradorRetriever,
         "Lakeland Terrier": .lakelandTerrier,
         "Lancashire Heeler": .lancashireHeeler,
         "Leonberger": .leonberger,
         "Lhasa Apso": .lhasaApso,
         "Lilac": .lilac,
         "Lionhead": .lionhead,
         "Lipizzan": .lipizzan,
         "Lizard": .lizard,
         "Llama": .llama,
         "Lop Eared": .lopEared,
         "Lory/Lorikeet": .loryLorikeet,
         "Lovebird": .lovebird,
         "Lowchen": .lowchen,
         "Macaw": .macaw,
         "Maine Coon": .maineCoon,
         "Maltese": .maltese,
         "Manchester Terrier": .manchesterTerrier,
         "Manx": .manx,
         "Maremma Sheepdog": .maremmaSheepdog,
         "Mastiff": .mastiff,
         "McNab": .mcnab,
         "Mini Rex": .miniRex,
         "Mini-Lop": .miniLop,
         "Miniature Horse": .miniatureHorse,
         "Miniature Pinscher": .miniaturePinscher,
         "Missouri Foxtrotter": .missouriFoxtrotter,
         "Morgan": .morgan,
         "Mountain Cur": .mountainCur,
         "Mountain Dog": .mountainDog,
         "Mouse": .mouse,
         "Munchkin": .munchkin,
         "Munsterlander": .munsterlander,
         "Mustang": .mustang,
         "Mynah": .mynah,
         "Neapolitan Mastiff": .neapolitanMastiff,
         "Nebelung": .nebelung,
         "Netherland Dwarf": .netherlandDwarf,
         "New Guinea Singing Dog": .newGuineaSingingDog,
         "New Zealand": .newZealand,
         "Newfoundland Dog": .newfoundlandDog,
         "Norfolk Terrier": .norfolkTerrier,
         "Norwegian Buhund": .norwegianBuhund,
         "Norwegian Elkhound": .norwegianElkhound,
         "Norwegian Forest Cat": .norwegianForestCat,
         "Norwegian Lundehund": .norwegianLundehund,
         "Norwich Terrier": .norwichTerrier,
         "Nova Scotia Duck-Tolling Retriever": .novaScotiaDuckTollingRetriever,
         "Ocicat": .ocicat,
         "Old English Sheepdog": .oldEnglishSheepdog,
         "Oriental Long Hair": .orientalLongHair,
         "Oriental Short Hair": .orientalShortHair,
         "Oriental Tabby": .orientalTabby,
         "Ostrich": .ostrich,
         "Otterhound": .otterhound,
         "Paint/Pinto": .paintPinto,
         "Palomino": .palomino,
         "Papillon": .papillon,
         "Parakeet (Other)": .parakeetOther,
         "Parrot (Other)": .parrotOther,
         "Parrotlet": .parrotlet,
         "Paso Fino": .pasoFino,
         "Patterdale Terrier (Fell Terrier)": .patterdaleTerrierFellTerrier,
         "Peacock/Pea fowl": .peacockPeaFowl,
         "Pekingese": .pekingese,
         "Percheron": .percheron,
         "Persian": .persian,
         "Peruvian Inca Orchid": .peruvianIncaOrchid,
         "Peruvian Paso": .peruvianPaso,
         "Petit Basset Griffon Vendeen": .petitBassetGriffonVendeen,
         "Pharaoh Hound": .pharaohHound,
         "Pheasant": .pheasant,
         "Pig": .pig,
         "Pigeon": .pigeon,
         "Pionus": .pionus,
         "Pit Bull Terrier": .pitBullTerrier,
         "Pixie-Bob": .pixieBob,
         "Plott Hound": .plottHound,
         "Podengo Portugueso": .podengoPortugueso,
         "Poicephalus/Senegal": .poicephalusSenegal,
         "Pointer": .pointer,
         "Polish": .polish,
         "Polish Lowland Sheepdog": .polishLowlandSheepdog,
         "Pomeranian": .pomeranian,
         "Pony": .pony,
         "Poodle": .poodle,
         "Portuguese Water Dog": .portugueseWaterDog,
         "Pot Bellied": .potBellied,
         "Prairie Dog": .prairieDog,
         "Presa Canario": .presaCanario,
         "Pug": .pug,
         "Puli": .puli,
         "Pumi": .pumi,
         "Quail": .quail,
         "Quaker Parakeet": .quakerParakeet,
         "Quarterhorse": .quarterhorse,
         "Ragamuffin": .ragamuffin,
         "Ragdoll": .ragdoll,
         "Rat": .rat,
         "Rat Terrier": .ratTerrier,
         "Redbone Coonhound": .redboneCoonhound,
         "Retriever": .retriever,
         "Rex": .rex,
         "Rhea": .rhea,
         "Rhinelander": .rhinelander,
         "Rhodesian Ridgeback": .rhodesianRidgeback,
         "Ringneck/Psittacula": .ringneckPsittacula,
         "Rosella": .rosella,
         "Rottweiler": .rottweiler,
         "Russian Blue": .russianBlue,
         "Saddlebred": .saddlebred,
         "Saint Bernard St. Bernard": .saintBernardStBernard,
         "Saluki": .saluki,
         "Samoyed": .samoyed,
         "Sarplaninac": .sarplaninac,
         "Satin": .satin,
         "Schipperke": .schipperke,
         "Schnauzer": .schnauzer,
         "Scottish Deerhound": .scottishDeerhound,
         "Scottish Fold": .scottishFold,
         "Scottish Terrier Scottie": .scottishTerrierScottie,
         "Sealyham Terrier": .sealyhamTerrier,
         "Selkirk Rex": .selkirkRex,
         "Setter": .setter,
         "Shar Pei": .sharPei,
         "Sheep": .sheep,
         "Sheep Dog": .sheepDog,
         "Shepherd": .shepherd,
         "Shetland Pony": .shetlandPony,
         "Shetland Sheepdog Sheltie": .shetlandSheepdogSheltie,
         "Shiba Inu": .shibaInu,
         "Shih Tzu": .shihTzu,
         "Siamese": .siamese,
         "Siberian": .siberian,
         "Siberian Husky": .siberianHusky,
         "Silky Terrier": .silkyTerrier,
         "Silver": .silver,
         "Silver Fox": .silverFox,
         "Silver Marten": .silverMarten,
         "Singapura": .singapura,
         "Skunk": .skunk,
         "Skye Terrier": .skyeTerrier,
         "Sloughi": .sloughi,
         "Smooth Fox Terrier": .smoothFoxTerrier,
         "Snake": .snake,
         "Snowshoe": .snowshoe,
         "Softbill (Other)": .softbillOther,
         "Somali": .somali,
         "South Russian Ovtcharka": .southRussianOvtcharka,
         "Spaniel": .spaniel,
         "Sphynx (hairless cat)": .sphynxHairlessCat,
         "Spitz": .spitz,
         "Staffordshire Bull Terrier": .staffordshireBullTerrier,
         "Standard Poodle": .standardPoodle,
         "Standardbred": .standardbred,
         "Sugar Glider": .sugarGlider,
         "Sussex Spaniel": .sussexSpaniel,
         "Swedish Vallhund": .swedishVallhund,
         "Tabby": .tabby,
         "Tabby - Brown": .tabbyBrown,
         "Tabby - Grey": .tabbyGrey,
         "Tabby - Orange": .tabbyOrange,
         "Tabby - black": .tabbyBlack,
         "Tabby - buff": .tabbyBuff,
         "Tabby - white": .tabbyWhite,
         "Tan": .tan,
         "Tarantula": .tarantula,
         "Tennessee Walker": .tennesseeWalker,
         "Terrier": .terrier,
         "Thai Ridgeback": .thaiRidgeback,
         "Thoroughbred": .thoroughbred,
         "Tibetan Mastiff": .tibetanMastiff,
         "Tibetan Spaniel": .tibetanSpaniel,
         "Tibetan Terrier": .tibetanTerrier,
         "Tiger": .tiger,
         "Tonkinese": .tonkinese,
         "Torbie": .torbie,
         "Tortoiseshell": .tortoiseshell,
         "Tosa Inu": .tosaInu,
         "Toy Fox Terrier": .toyFoxTerrier,
         "Treeing Walker Coonhound": .treeingWalkerCoonhound,
         "Turkish Angora": .turkishAngora,
         "Turkish Van": .turkishVan,
         "Turtle": .turtle,
         "Tuxedo": .tuxedo,
         "Unknown": .unknown,
         "Vietnamese Pot Bellied": .vietnamesePotBellied,
         "Vizsla": .vizsla,
         "Warmblood": .warmblood,
         "Weimaraner": .weimaraner,
         "Welsh Corgi": .welshCorgi,
         "Welsh Springer Spaniel": .welshSpringerSpaniel,
         "Welsh Terrier": .welshTerrier,
         "West Highland White Terrier Westie": .westHighlandWhiteTerrierWestie,
         "Wheaten Terrier": .wheatenTerrier,
         "Whippet": .whippet,
         "White German Shepherd": .whiteGermanShepherd,
         "Wire Fox Terrier": .wireFoxTerrier,
         "Wire-haired Pointing Griffon": .wireHairedPointingGriffon,
         "Wirehaired Terrier": .wirehairedTerrier,
         "Xoloitzcuintle/Mexican Hairless": .xoloitzcuintleMexicanHairless,
         "Yellow Labrador Retriever": .yellowLabradorRetriever,
         "Yorkshire Terrier Yorkie": .yorkshireTerrierYorkie
    ]
}
